# # # # # # # # # # # # # # 
# 1. datasets
# # # # # # # # # # # # # # 
dataset: # Required.
  type: pascal_semi # pascal voc: pascal_semi; cityscapce: cityscapes_semi
  train:
    data_root: /data1/lcx/maozan/SemiSL/DATASETS/VOCdevkit/VOC2012 # 修改为你自己的数据路径
    data_list: ./data/splitsall/pascal/662/labeled.txt # 对应不同比例的数据划分
    batch_size: 8 # 单张显卡batch_size 固定为8，两张一共16
    flip: True
    rand_resize: [0.5, 2.0]
    resize_base_size: 500
    crop:
      type: rand
      size: [513, 513]
    #---- 1) strong data augs ----#
    strong_aug:
      num_augs: 3                       
      flag_use_random_num_sampling: True        
  val:
    data_root: /data1/lcx/maozan/SemiSL/DATASETS/VOCdevkit/VOC2012
    data_list: ./data/splitsall/pascal/val.txt
    batch_size: 1
  n_sup: 662 # 修改数据划分时候，这里也要改变
  workers: 4
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  ignore_label: 255

# # # # # # # # # # # # # # 
# 2. training params
# # # # # # # # # # # # # # 
trainer: # Required.
  epochs: 80
  sup_only_epoch: 0 # 设置为0，即全部是半监督训练，设置为epoch数，如80，即全部是有监督训练
  evaluate_student: True
  optimizer:
    type: SGD
    kwargs:
      lr: 0.001  # 0.001:8*2gpus, 4*4gpus; 0.002:8*4gpus.
      momentum: 0.9
      weight_decay: 0.0001
  lr_scheduler:
    mode: poly
    kwargs:
      power: 0.9
  # # # # # # # # # # # # # # 
  # unsupervised loss
  # # # # # # # # # # # # # # 
  unsupervised:
    flag_extra_weak: False
    threshold: 0.95           # ============================================================================= <<abl1-threshold>>: [0.7, 0.75, 0.8, 0.85, 0.9, 0.95]
    loss_weight: 1.0          # ============================================================================= << abl2-weight >> : [1.0, 1.5, 2.0, 2.5, 3.0, 4.0]
    #------ 2)strong augs ------#
    random_strong_aug: 4
    use_strong: True
    use_rotate: False
    use_perspective: False
    use_Affine: False
    use_cutout: False
    use_cutmix: True
    use_cutmix_labelinj: False
    use_cutmix_adaptive: False
    use_cutmix_trigger_prob: 1.0

# # # # # # # # # # # # # # 
# 3. output files, and loss
# # # # # # # # # # # # # # 
saver:
  snapshot_dir: checkpoints
  pretrain: ''
  use_tb: False
  auto_resume: False

criterion:
  type: CELoss
  kwargs:  
    use_weight: False

# # # # # # # # # # # # # # 
# 4. models
# # # # # # # # # # # # # # 
net: # Required.
  num_classes: 21
  sync_bn: True
  ema_decay: 0.999
  encoder:
    type: pseudo.models.resnet.resnet50 # r50时候， r101时候用下面注释的两行
    pretrain: ./pretrained/resnet50.pth
    # type: augseg.models.resnet.resnet101
    # pretrain: ./pretrained/resnet101.pth
    kwargs:
      zero_init_residual: True
      multi_grid: True
      replace_stride_with_dilation: [False, False, True]  # [output_stride = 16]
      # replace_stride_with_dilation: [False, True, True]  # [output_stride = 8]
  decoder:
    type: pseudo.models.decoder.dec_deeplabv3_plus
    kwargs:
      inner_planes: 256
      low_conv_planes: 48
      dilations: [6, 12, 18]  # [output_stride = 16]
      # dilations: [12, 24, 36]  # [output_stride = 8]
